version: '3.5'

services:
    nginx:
        image: nexus.prod.uci.cu/nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php5_fpm
        volumes:
            #- ./conf/sipac_2.4:/var/www/html/
            - ./logs/nginx/:/var/log/nginx
            - ./conf/nginx.conf:/etc/nginx/nginx.conf
            - ./conf/default-nginx.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx.pem:/etc/ssl/certs/nginx.pem
            - ./conf/nginx.key:/etc/ssl/private/nginx.key
    
    php5_fpm:
        image: nexus.prod.uci.cu/rmolinet/sipac-php-alpine:3.0
        volumes:
            #- ./conf/sipac_2.4:/var/www/html/
            - ./conf/php.ini:/usr/local/etc/php/php.ini
            - ./conf/kcachegrind_files:/usr/local/reportes_kcachegrind
        expose:
            - "9004"
        extra_hosts:
            - "dockerhost:172.17.0.1"

   postgresql:
        image: nexus.prod.uci.cu/postgres:alpine
        ports:
            - "5432:5432"   
        volumes:
            #- ./conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
            - data_postgresql:/var/lib/postgresql/data
            - binarios_postgres:/usr/local/bin    
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres

    pgadmin4:
        image: nexus.prod.uci.cu/rmolinet/sipac-pgadmin4:2.1
        ports:
            - "5050:5050"
        depends_on:
            - postgresql
        volumes:
            - binarios_postgres:/usr/local/bin/postgres_binaries
            - ./conf/pgadmin4_storage:/var/lib/pgadmin/storage
        environment:
            DEFAULT_USER: admin@uci.cu
            #DEFAULT_PASSWORD: admin

volumes:
    data_postgresql:
    binarios_postgres:
